"""Agent workflow: retrieval -> prompt -> LLM -> strategy -> execution.

Single-call flow:
1. Retrieve algorithm guides relevant to the problem from the knowledge base
2. Render the evolvable prompt genome into system/user prompts
3. Call the LLM to obtain the strategy JSON
4. Parse and validate it into a StrategyGenome (fall back to random if invalid)
5. Deterministically execute the strategy and return the evaluation result
"""

import logging

import numpy as np

from evoagent.agent.knowledge_base import KnowledgeBase
from evoagent.agent.llm import LLMClient, build_llm_client, timed_chat
from evoagent.agent.prompts import build_system_prompt, build_user_prompt
from evoagent.agent.strategy_generator import parse_strategy_with_fallback
from evoagent.core.genome_prompt import EvolvablePrompt
from evoagent.core.individual import AgentIndividual
from evoagent.environment.problem import OptimizationProblem
from evoagent.evolution.strategy import StrategyExecutor
from evoagent.utils.random import get_global_rng, set_global_seed

logger = logging.getLogger("evoagent.agent")


class AgentWorkflow:
    """LLM Agent workflow: prompt genome -> strategy -> evaluation result."""

    def __init__(
        self,
        problem: OptimizationProblem,
        budget: int = 300,
        llm: LLMClient | None = None,
        knowledge_base: KnowledgeBase | None = None,
        executor: StrategyExecutor | None = None,
        weights: np.ndarray | None = None,
    ):
        """Initialize.

        Args:
            problem: Optimization problem
            budget: Evaluation budget per strategy
            llm: LLM client (auto-built by default; falls back to mock when no key is set)
            knowledge_base: Knowledge base
            executor: Strategy executor
            weights: Scalarization weights (for the multi-objective semiconductor scenario)
        """
        self.problem = problem
        self.budget = budget
        self.llm = llm or build_llm_client()
        self.knowledge_base = knowledge_base or KnowledgeBase()
        self.executor = executor or StrategyExecutor(problem, weights=weights)
        self.weights = weights
        self.call_count = 0

    def run(
        self,
        prompt: EvolvablePrompt | None = None,
        seed: int | None = None,
        mode: str = "prompt",
    ) -> AgentIndividual:
        """Run one complete Agent flow.

        Args:
            prompt: Evolvable prompt genome (may be None in structure mode)
            seed: Random seed (None uses the global RNG)
            mode: SEW dual mode: prompt (prompt-guided) / structure (neutral prompt, no genome constraints)

        Returns:
            Individual with evaluation results (genome is the strategy generated by the LLM)
        """
        rng = get_global_rng() if seed is None else np.random.default_rng(seed)
        if mode == "structure":
            system = build_system_prompt(None)
            user = build_user_prompt(None, self.problem)
        else:
            if prompt is None:
                from evoagent.core.genome_prompt import default_prompt

                prompt = default_prompt()
            system = build_system_prompt(prompt)
            knowledge = self.knowledge_base.retrieve(
                f"{self.problem.name} {prompt.tool_preference} {prompt.thinking_style}"
            )
            user = build_user_prompt(prompt, self.problem, knowledge)
        try:
            data = timed_chat(self.llm, system, user)
            self.call_count += 1
        except Exception as e:  # noqa: BLE001 - LLM failures need a fallback
            logger.warning("LLM 调用失败（%s），回退随机策略", e)
            data = {}
        genome = parse_strategy_with_fallback(data, rng)
        result = self.executor.run(genome, budget=self.budget, rng=rng)
        individual = AgentIndividual(agent_id=f"wf-{self.call_count}", genome=genome)
        individual.fitness = result.best_fitness
        individual.objectives = self.problem.objectives_clean(result.best_params)
        individual.best_params = result.best_params
        individual.n_evals = result.n_evals
        individual.n_improvements = result.n_improvements
        individual.mode = mode
        individual.result = result
        return individual

    def reset_call_count(self) -> None:
        """Reset the call counter."""
        self.call_count = 0
